Nome: Caio Ruiz Coldebella

RA: 232621


---

#L1 - Familiarizando-se com o *numpy*#

**Objetivo:** Familiarização com o ambiente Google Colab, com a biblioteca *numpy* e com a estrutura ndarray.

**Motivação:** Algoritmos de processamento de imagens exigem desenvoltura na manipulação de arrays.

---

### Exercício 1 ###

Documente o código abaixo com uma frase que explique o que cada linha está fazendo. Altere o código para que seja gerada um array b, idêntico ao a, com números inteiros no qual cada elemento ocupe 8 bits na memória. 

Referências:

[1] https://numpy.org/doc/stable/user/absolute_beginners.html

[2] https://numpy.org/doc/stable/reference/arrays.dtypes.html


In [8]:
# Primeiro exercício
import numpy as np #importando a biblioteca numpy
a = np.array( [2,3,4,-1,-2,256, 270] ,'float') #criando um array de dimensao 1 com elementos do tipo float
print ('Dimensões: a.shape=', a.shape) # imprime na tela o numero de elementos de cada dimensao
print ('Tipo dos elementos: a.dtype=', a.dtype) # imprime o tipo dos elementos
print ('Imprimindo o array completo:\n a=',a) # imprime o array
m = a.max() # armazena na variavel m o maior elemento do array
print(m) # imprime m (maior elemento do array)
print(m.dtype) #imprime o tipo de m
#b = a//a.max() # faz a divisao inteira de cada elemento do array a pelo maior elemento do array e armazena no array b
b = np.array(a.copy(),dtype='i8') #gerando um array b, idêntico ao a, com números inteiros no qual cada elemento ocupa 8 bits na memória.
print (b) #imprime b
print(b.dtype) #imprimindo o tipo de b

Dimensões: a.shape= (7,)
Tipo dos elementos: a.dtype= float64
Imprimindo o array completo:
 a= [  2.   3.   4.  -1.  -2. 256. 270.]
270.0
float64
[  2   3   4  -1  -2 256 270]
int64




---


### Exercício 2 ###

Considere o array já inicializado b.

Inclua nas funções print já codificadas, a função numpy que recupera a informação desejada.

Adicione ao código uma linha que recupere e imprima o número 5.6.

Adicione ao código uma ou mais linhas que processem o array b e retornem o array c = [2.3, 5.6] unidimensional.

Referências:

[3] https://numpy.org/doc/stable/reference/arrays.ndarray.html

[4] https://numpy.org/doc/stable/user/basics.indexing.html

In [28]:
b = np.array( [[[1.5, 2.3, 5.2]],
                [[4.2, 5.6, 4.4]]] )
print ('O shape desse array é:',b.shape)
print ('O número de dimensões desse array é:',b.ndim)
print ('Os elementos desse array são do tipo:',b.dtype)
print ('O número de colunas desse array é:',b.shape[2])
print ('O número de linhas desse array é:',b.shape[1])
print(b[np.where(b == 5.6)]) # recuperando e imprimindo o número 5.6
c = (b.reshape(2,3)).copy() # manipulando o array b
c = np.array_split(c,3,axis=1)
c = c[1].reshape(2)
print(c) # array c
print(c.ndim) # unidimensional

O shape desse array é: (2, 1, 3)
O número de dimensões desse array é: 3
Os elementos desse array são do tipo: float64
O número de colunas desse array é: 3
O número de linhas desse array é: 1
[5.6]
[2.3 5.6]
1




---


### Exercício 3 ###

Utilizando o *numpy*:

(a) Crie uma matriz 150x150 com todos os elementos iguais a zero.

(b) Modifique a matriz para que no seu centro, haja uma região quadrada de tamanho 50x50 de elementos iguais a 1. Veja abaixo uma analogia do resultado experado.

(c) Pesquise funções associadas e meça o tempo de execução do código resultante deste exercício.

```
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 1 1 1 0 0 0
0 0 0 1 1 1 0 0 0
0 0 0 1 1 1 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0```



In [67]:
import time
start = time.time()
matriz = np.zeros((150,150),dtype='i4')
print(matriz.shape)
for i in range(50,99,1):
  for j in range(50,99,1):
    matriz[i][j] = 1
np.set_printoptions(threshold=np.inf,linewidth=320)
print(matriz)
end = time.time()
print("Tempo de execucao:",end-start,"segundos")

(150, 150)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

---
👂 🧐 Comente abaixo as principais dificuldades que teve na realização das atividades. 

---
